import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Provider } from './context/provider';
import { Bricolage_Grotesque } from 'next/font/google';
import { Toaster } from 'sonner';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const skilletRegular = localFont({
  src: './fonts/Skillet-Regular.woff',
  variable: '--font-skillet_regular',
  weight: '400',
});

const skilletCondensed = localFont({
  src: './fonts/Skillet-Condensed.woff',
  variable: '--font-skillet_condensed',
  weight: '400',
});

const bricolageFont = Bricolage_Grotesque({
  subsets: ['latin'],
  weight: '800',
  variable: '--font-rum_raisin',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const fonts = [geistSans.variable, geistMono.variable, bricolageFont.variable, skilletRegular.variable, skilletCondensed.variable];

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fonts.join(' ')} antialiased`}>
        <Toaster />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
